-- CreateEnum
CREATE TYPE "CanonicalFixtureType" AS ENUM ('HIGH_BAY', 'LOW_BAY', 'TROFFER', 'FLAT_PANEL', 'DOWNLIGHT', 'RECESSED_CAN', 'CYLINDER', 'VAPOR_TIGHT', 'WALL_PACK', 'WALL_MOUNT', 'SCONCE', 'FLOOD', 'AREA_SITE', 'ROADWAY', 'CANOPY', 'GARAGE', 'LINEAR_SUSPENDED', 'LINEAR_SURFACE', 'LINEAR_SLOT', 'STRIP', 'WRAP', 'PENDANT', 'SURFACE_MOUNT', 'TRACK', 'BOLLARD', 'LANDSCAPE', 'POST_TOP', 'STEP_LIGHT', 'UNDER_CABINET', 'EXIT_EMERGENCY', 'VANITY', 'COVE', 'RETROFIT_KIT', 'CONTROLS', 'SENSOR', 'DRIVER', 'POWER_SUPPLY', 'MODULAR_WIRING', 'POLE', 'ARM_BRACKET', 'ACCESSORY', 'SPORTS_LIGHTING', 'UV_C', 'SURGICAL', 'CLEANROOM', 'VANDAL_RESISTANT', 'BEHAVIORAL', 'DECORATIVE', 'OTHER');

-- AlterTable
ALTER TABLE "Product" ADD COLUMN "canonicalFixtureType" "CanonicalFixtureType",
ADD COLUMN "canonicalFixtureConfidence" DOUBLE PRECISION,
ADD COLUMN "canonicalFixtureSource" TEXT,
ADD COLUMN "canonicalFixtureEvidence" TEXT;

-- CreateIndex
CREATE INDEX "Product_canonicalFixtureType_idx" ON "Product"("canonicalFixtureType");
